/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param id 
 * @param name The name of the character.
 * @param description A short bio or description of the character.
 * @param modified 
 * @param resourceURI The canonical URL identifier for this resource.
 * @param urls 
 * @param thumbnail 
 * @param comics 
 * @param stories 
 * @param events 
 * @param series 
 */
data class Character (

    val id: Int? = null,
    /* The name of the character. */
    val name: String? = null,
    /* A short bio or description of the character. */
    val description: String? = null,
    val modified: java.time.LocalDate? = null,
    /* The canonical URL identifier for this resource. */
    val resourceURI: String? = null,
    val urls: Array<Any>? = null,
    val thumbnail: Image? = null,
    val comics: ComicList? = null,
    val stories: StoryList? = null,
    val events: EventList? = null,
    val series: SeriesList? = null
) {
}