/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param type A description of the date (e.g. onsale date, FOC date).
 * @param date 
 */
data class ComicDate (

    /* A description of the date (e.g. onsale date, FOC date). */
    val type: String? = null,
    val date: java.time.LocalDate? = null
) {
}