/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param id 
 * @param firstName The first name of the creator.
 * @param middleName The middle name of the creator.
 * @param lastName The last name of the creator.
 * @param suffix The suffix or honorific for the creator.
 * @param fullName The full name of the creator (a space-separated concatenation of the above four fields).
 * @param modified 
 * @param resourceURI The canonical URL identifier for this resource.
 * @param urls 
 * @param thumbnail 
 * @param series 
 * @param stories 
 * @param comics 
 * @param events 
 */
data class Creator (

    val id: Int? = null,
    /* The first name of the creator. */
    val firstName: String? = null,
    /* The middle name of the creator. */
    val middleName: String? = null,
    /* The last name of the creator. */
    val lastName: String? = null,
    /* The suffix or honorific for the creator. */
    val suffix: String? = null,
    /* The full name of the creator (a space-separated concatenation of the above four fields). */
    val fullName: String? = null,
    val modified: java.time.LocalDate? = null,
    /* The canonical URL identifier for this resource. */
    val resourceURI: String? = null,
    val urls: Array<Any>? = null,
    val thumbnail: Image? = null,
    val series: SeriesList? = null,
    val stories: StoryList? = null,
    val comics: ComicList? = null,
    val events: EventList? = null
) {
}