/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param id 
 * @param title The title of the event.
 * @param description A description of the event.
 * @param resourceURI The canonical URL identifier for this resource.
 * @param urls 
 * @param modified 
 * @param start 
 * @param end 
 * @param thumbnail 
 * @param comics 
 * @param stories 
 * @param series 
 * @param characters 
 * @param creators 
 * @param next 
 * @param previous 
 */
data class Event (

    val id: Int? = null,
    /* The title of the event. */
    val title: String? = null,
    /* A description of the event. */
    val description: String? = null,
    /* The canonical URL identifier for this resource. */
    val resourceURI: String? = null,
    val urls: Array<Any>? = null,
    val modified: java.time.LocalDate? = null,
    val start: java.time.LocalDate? = null,
    val end: java.time.LocalDate? = null,
    val thumbnail: Image? = null,
    val comics: ComicList? = null,
    val stories: StoryList? = null,
    val series: SeriesList? = null,
    val characters: CharacterList? = null,
    val creators: CreatorList? = null,
    val next: EventSummary? = null,
    val previous: EventSummary? = null
) {
}