/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param id 
 * @param title The canonical title of the series.
 * @param description A description of the series.
 * @param resourceURI The canonical URL identifier for this resource.
 * @param urls 
 * @param startYear 
 * @param endYear 
 * @param rating The age-appropriateness rating for the series.
 * @param modified 
 * @param thumbnail 
 * @param comics 
 * @param stories 
 * @param events 
 * @param characters 
 * @param creators 
 * @param next 
 * @param previous 
 */
data class Series (

    val id: Int? = null,
    /* The canonical title of the series. */
    val title: String? = null,
    /* A description of the series. */
    val description: String? = null,
    /* The canonical URL identifier for this resource. */
    val resourceURI: String? = null,
    val urls: Array<Any>? = null,
    val startYear: Int? = null,
    val endYear: Int? = null,
    /* The age-appropriateness rating for the series. */
    val rating: String? = null,
    val modified: java.time.LocalDate? = null,
    val thumbnail: Image? = null,
    val comics: ComicList? = null,
    val stories: StoryList? = null,
    val events: EventList? = null,
    val characters: CharacterList? = null,
    val creators: CreatorList? = null,
    val next: SeriesSummary? = null,
    val previous: SeriesSummary? = null
) {
}