/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models


/**
 * 
 * @param resourceURI The path to the individual series resource.
 * @param name The canonical name of the series.
 */
data class SeriesSummary (

    /* The path to the individual series resource. */
    val resourceURI: String? = null,
    /* The canonical name of the series. */
    val name: String? = null
) {
}