/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param available 
 * @param returned 
 * @param collectionURI The path to the full list of stories in this collection.
 * @param items 
 */
data class StoryList (
    val available: Int? = null,
    val returned: Int? = null,
    /* The path to the full list of stories in this collection. */
    val collectionURI: String? = null,
    val items: Array<Any>? = null
) {
}