/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models

/**
 * 
 * @param id 
 * @param title The story title.
 * @param description A short description of the story.
 * @param resourceURI The canonical URL identifier for this resource. 
 * @param type The story type e.g. interior story, cover, text story.
 * @param modified 
 * @param thumbnail 
 * @param comics 
 * @param series 
 * @param events 
 * @param characters 
 * @param creators 
 * @param originalissue 
 */
data class Story (

    val id: Int? = null,
    /* The story title. */
    val title: String? = null,
    /* A short description of the story. */
    val description: String? = null,
    /* The canonical URL identifier for this resource.  */
    val resourceURI: String? = null,
    /* The story type e.g. interior story, cover, text story. */
    val type: String? = null,
    val modified: java.time.LocalDate? = null,
    val thumbnail: Image? = null,
    val comics: ComicList? = null,
    val series: SeriesList? = null,
    val events: EventList? = null,
    val characters: CharacterList? = null,
    val creators: CreatorList? = null,
    val originalissue: ComicSummary? = null
) {
}