/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.botob.marvelapi.client.models


/**
 * 
 * @param resourceURI The path to the individual story resource.
 * @param name The canonical name of the story.
 * @param type The type of the story (interior or cover).
 */
data class StorySummary (

    /* The path to the individual story resource. */
    val resourceURI: String? = null,
    /* The canonical name of the story. */
    val name: String? = null,
    /* The type of the story (interior or cover). */
    val type: String? = null
) {
}